services:
  - type: web
    name: video-transcriber
    env: python
    region: oregon # Optional: can also be frankfurt, singapore, etc.
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --reload
    envVars:
      - key: ASSEMBLY_AI_API_KEY
        sync: false
