services:
  - type: web
    name: video-transcriber
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: ASSEMBLY_AI_API_KEY
        sync: false
